e=set()
s=int(input("Enter first no."))
e.add(s)
s=int(input("Enter second"))
e.add(s)
s=int(input("Enter Third no."))
e.add(s)
s=int(input("Enter fourth no."))
e.add(s)
s=int(input("Enter fifth no."))
e.add(s)
s=int(input("Enter sixth no."))
e.add(s)
s=int(input("Enter Seventh no."))
e.add(s)
print("your all unique numbers are",e)
